### ISSUE TITLE
Make map parser

### ISSUE THREAD

**Issue by blauks** [AndreasWintherMoen/project-cows#1]
Parse path and map from a file. 👍

This will increase modifiability. 🗺

**Comment by AndreasWintherMoen** [comment]
For now, we only have walkable and non-walkable tiles (TileTypes PATH & GRASS). This should be a sufficient map file until we add more tile types. 

0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000011110000
0000000110011100
0000000100000100
0000000100000111
0000000100000000
1111111100000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000

**Comment by blauks** [comment]
👍
