### ISSUE TITLE
Fix cancel tower placement button

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/project-cows#23]
In the planning defense phase, when the user selects a tower to place and then clicks the cancel button, the tile click is also registered and the tower is placed on the given tile. I'm not sure how to solve this, but perhaps do some sort of ordering on the click subscribers, and set button priority higher than TowerSpawner?

**Comment by blauks** [comment]
Hmm... Very weird

**Comment by blauks** [comment]
Putting this issue on pause, since we might not need to fix it after all:-)

**Comment by AndreasWintherMoen** [comment]
Closed. Doesn't apply anymore after making ActionPanel.
