### ISSUE TITLE
Implement Map.reverse()

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/project-cows#26]
I think it would be useful to be able to flip the map horizontally, since one player's map will just be a mirrored version of the other player's map. Could you look into this @blauks ?

**Comment by AndreasWintherMoen** [comment]
Maybe it should be called **Map.flip()** ?

**Comment by blauks** [comment]
I can look into this!

**Comment by haakon-gun** [comment]
I will look into this!

**Comment by blauks** [comment]
Is this finished?
