### ISSUE TITLE
Setup websocket connection

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/project-cows#4]
Basically setup the GSS (GameStateServer) with a WebSocket server connection. Then, create a WebSocket connection module in the client project, and allow the two to communicate. No game logic needs to be implemented for now, just send a hello world message.

**Comment by blauks** [comment]
Since I want to focus a bit more on _cool_ IT-architecture, I can join you on this issue @pmAllport if you feel like you need any help 👍

**Comment by blauks** [comment]
Overview of work:
- Jonathan
    - API between client and server
    - Give user UUID
    - Make possible for user to create game
    - Make possible for user to join game
- Patrick
     - Logic between API endpoints and internal game mapping structure
     - Logic to map a user(ClientConnection) to a game
     - Logic to create gamecodes 
     - Validate client join game requests

For future work:
- Validate which user is attacker and defender
