### ISSUE TITLE
Implement Simulation module

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/project-cows#5]
This module has one public function which receives a GameState object, AttackInstructions (i.e. UnitList) and DefendInstructions (i.e. TowerList), and returns a RoundSimulation object. For now, this can be implemented in the client, but once the server infrastructure is created we can move it to SS.

**Comment by Nicolaad** [comment]
me and @fredrikbw are looking into it!

**Comment by fredrikbw** [comment]
Waiting for #16 to add availability for finding the next target of a tower

**Comment by Nicolaad** [comment]
implemented with #32
