### ISSUE TITLE
Send instructions lists to GSS on start button

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/project-cows#58]

**Comment by AndreasWintherMoen** [comment]
Look at this hagegnom

![bitmoji](https://sdk.bitmoji.com/render/panel/f2af1d6e-06e9-4e30-ad4e-160790dd2fa3-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)

**Comment by blauks** [comment]
LGTM!
