### ISSUE TITLE
Game balance for user testing

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/project-cows#65]

**Comment by blauks** [comment]
![bitmoji](https://camo.githubusercontent.com/5681f2c96c3a88f8b4010cd6b16de8ee308ab855cdfda8d965c240d2cbb012c0/68747470733a2f2f73646b2e6269746d6f6a692e636f6d2f72656e6465722f70616e656c2f31333933643638622d326664622d346363332d383235622d3131393066623938373631322d33346563663139332d323762632d343030642d623065302d3339373238326430623961342d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)
